name: Bai07 Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on:
  push:
    branches: [ "main" ] ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Bai07 Pipeline
      uses: actions/setup-java@v3
      with:
        java-version:
  push:
    branches: [ "main" ] '17'
        distribution:
  push:
    branches: [ "main" ] 'temurin'
        
    - name: Bai07 Pipeline
      run: mvn -f Bai07/pom.xml checkstyle:check
      continue-on-error: true
      
    - name: Bai07 Pipeline
      uses: dbelyaev/action-checkstyle@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        checkstyle_config: google_checks.xml
