name: Bai03 Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Bai03 Pipeline
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Bai03 Pipeline
      run: mvn clean package -f Bai03/pom.xml
      
    - name: Bai03 Pipeline
      uses: actions/upload-artifact@v3
      with:
        name: Bai03 Pipeline
        path: target/*.jar
