name: Bai10 Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bai10 Pipeline
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - name: Bai10 Pipeline
        run: mvn -f Bai10/pom.xml package
